version: '3.7'

services:
  tradovate-bot:
    container_name: tradovate-bot
    build:
      context: ./
      target: dev-stage
      # target: production-stage
    command: npx pm2-runtime ecosystem.config.js
    networks:
      - internal
    volumes:
      - ./config:/srv/config
      - ./app:/srv/app
      - ./agents:/srv/agents
      - ./public:/srv/public
      - ./migrations:/srv/migrations
      - ./scripts:/srv/scripts
      - ./ecosystem.config.js:/srv/ecosystem.config.js
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - TRADOVATE_MODE=test
      # - TRADOVATE_MODE=live
      - TRADOVATE_REDIS_HOST=tradovate-redis
      - TRADOVATE_REDIS_PORT=6379
      - TRADOVATE_REDIS_PASSWORD=secretp422
      - TRADOVATE_POSTGRES_HOST=tradovate-postgres
      - TRADOVATE_POSTGRES_PORT=5432
      - TRADOVATE_POSTGRES_DATABASE=tradovate_bot
      - TRADOVATE_POSTGRES_USER=tradovate
      - TRADOVATE_POSTGRES_PASSWORD=tradovate_pass
    ports:
      - 8080:80
    logging:
      driver: 'json-file'
      options:
        max-size: '1G'

  tradingview:
    container_name: tradingview
    build:
      context: ./tradingview
    networks:
      - internal
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      # https://docs.python.org/3/howto/logging.html#logging-levels
      - TRADINGVIEW_LOG_LEVEL=INFO
    ports:
      - 8082:8080
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'

  tradovate-redis:
    container_name: tradovate-redis
    image: redis:6.2.4
    sysctls:
      net.core.somaxconn: 1024
    restart: unless-stopped
    networks:
      - internal
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass secretp422

  tradovate-postgres:
    container_name: tradovate-postgres
    image: postgres:15
    restart: unless-stopped
    networks:
      - internal
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: tradovate_bot
      POSTGRES_USER: tradovate
      POSTGRES_PASSWORD: tradovate_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  internal:
    driver: bridge
    # driver_opts:
    #     com.docker.network.driver.mtu: 1442

volumes:
  redis_data:
  postgres_data:
