version: '3.7'

services:
  tradovate-bot:
    container_name: tradovate-bot
    image: donaldit/tradovate-trading-bot:latest
    networks:
      - internal
    env_file:
      - .env
    restart: unless-stopped
    environment:
      # - TRADOVATE_MODE=test
      - TRADOVATE_MODE=live
      - TRADOVATE_REDIS_HOST=tradovate-redis
      - TRADOVATE_REDIS_PORT=6379
      - TRADOVATE_REDIS_PASSWORD=secretp422
    ports:
      - 8080:80
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'

  tradingview:
    container_name: tradingview
    image: donaldit/tradovate-trading-bot:tradingview
    networks:
      - internal
    restart: unless-stopped
    environment:
      # https://docs.python.org/3/howto/logging.html#logging-levels
      - TRADINGVIEW_LOG_LEVEL=INFO
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'

  tradovate-redis:
    container_name: tradovate-redis
    image: redis:6.2.4
    sysctls:
      net.core.somaxconn: 1024
    networks:
      - internal
    restart: unless-stopped
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass secretp422

  tradovate-mongo:
    container_name: tradovate-mongo
    image: mongo:3.2.20-jessie
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - mongo_data:/data/db

networks:
  internal:
    driver: bridge
    # driver_opts:
    #     com.docker.network.driver.mtu: 1442

volumes:
  redis_data:
  mongo_data:
