version: '3.7'

services:
  tradovate-bot:
    container_name: tradovate-bot
    build:
      context: ./
      target: dev-stage
      # target: production-stage
    networks:
      - internal
    volumes:
      - ./config:/srv/config
      - ./app:/srv/app
      - ./public:/srv/public
      - ./migrations:/srv/migrations
      - ./scripts:/srv/scripts
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - TRADOVATE_MODE=test
      # - TRADOVATE_MODE=live
      - TRADOVATE_REDIS_HOST=tradovate-redis
      - TRADOVATE_REDIS_PORT=6379
      - TRADOVATE_REDIS_PASSWORD=secretp422
    ports:
      - 8080:80
    logging:
      driver: 'json-file'
      options:
        max-size: '1G'

  tradingview:
    container_name: tradingview
    build:
      context: ./tradingview
    networks:
      - internal
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      # https://docs.python.org/3/howto/logging.html#logging-levels
      - TRADINGVIEW_LOG_LEVEL=INFO
    ports:
      - 8082:8080
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'

  tradovate-redis:
    container_name: tradovate-redis
    image: redis:6.2.4
    sysctls:
      net.core.somaxconn: 1024
    restart: unless-stopped
    networks:
      - internal
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass secretp422

  tradovate-mongo:
    container_name: tradovate-mongo
    image: mongo:3.2.20-jessie
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - mongo_data:/data/db

  tradovate-mongo-express:
    container_name: tradovate-mongo-express
    image: mongo-express:0.54
    restart: unless-stopped
    networks:
      - internal
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: tradovate-mongo

networks:
  internal:
    driver: bridge
    # driver_opts:
    #     com.docker.network.driver.mtu: 1442

volumes:
  redis_data:
  mongo_data:
