/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Tradovate Auto Trading Bot API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export type DashboardSummaryBotStatus =
  (typeof DashboardSummaryBotStatus)[keyof typeof DashboardSummaryBotStatus];

export const DashboardSummaryBotStatus = {
  live: "live",
  simulated: "simulated",
  stopped: "stopped",
} as const;

export interface DashboardSummary {
  totalBalance: number;
  dailyPnl: number;
  dailyPnlPercent: number;
  weeklyPnl: number;
  openPositions: number;
  botStatus: DashboardSummaryBotStatus;
  totalTrades: number;
  winRate: number;
}

export type PositionSide = (typeof PositionSide)[keyof typeof PositionSide];

export const PositionSide = {
  long: "long",
  short: "short",
} as const;

export interface Position {
  id: string;
  symbol: string;
  side: PositionSide;
  entryPrice: number;
  currentPrice: number;
  size: number;
  unrealizedPnl: number;
  unrealizedPnlPercent: number;
  openedAt: string;
}

export interface KillSwitchResult {
  success: boolean;
  closedCount: number;
  message: string;
}

export type TradeSide = (typeof TradeSide)[keyof typeof TradeSide];

export const TradeSide = {
  long: "long",
  short: "short",
} as const;

export interface Trade {
  id: string;
  symbol: string;
  side: TradeSide;
  entryPrice: number;
  exitPrice: number;
  size: number;
  realizedPnl: number;
  realizedPnlPercent: number;
  openedAt: string;
  closedAt: string;
}

export interface Strategy {
  id: string;
  name: string;
  enabled: boolean;
  maxPositions: number;
  riskPerTrade: number;
  stopLossPercent: number;
  takeProfitPercent: number;
  tradingHoursStart: string;
  tradingHoursEnd: string;
  instruments: string[];
  updatedAt: string;
}

export interface UpdateStrategyBody {
  name?: string;
  enabled?: boolean;
  maxPositions?: number;
  riskPerTrade?: number;
  stopLossPercent?: number;
  takeProfitPercent?: number;
  tradingHoursStart?: string;
  tradingHoursEnd?: string;
  instruments?: string[];
}

export type LogEntrySeverity =
  (typeof LogEntrySeverity)[keyof typeof LogEntrySeverity];

export const LogEntrySeverity = {
  info: "info",
  warning: "warning",
  error: "error",
} as const;

export type LogEntryContext = { [key: string]: unknown };

export interface LogEntry {
  id: string;
  timestamp: string;
  severity: LogEntrySeverity;
  message: string;
  context?: LogEntryContext;
}

export interface StrategyPerformance {
  winRate: number;
  currentDrawdown: number;
  maxDrawdown: number;
  totalTrades: number;
  winningTrades: number;
  losingTrades: number;
  riskRewardRatio: number;
  avgWin: number;
  avgLoss: number;
  profitFactor: number;
  sharpeRatio: number;
}

export type ListTradesParams = {
  limit?: number;
  offset?: number;
};

export type ListLogsParams = {
  limit?: number;
  severity?: ListLogsSeverity;
};

export type ListLogsSeverity =
  (typeof ListLogsSeverity)[keyof typeof ListLogsSeverity];

export const ListLogsSeverity = {
  info: "info",
  warning: "warning",
  error: "error",
} as const;

export interface OhlcBar {
  timestamp: string;
  open: number;
  high: number;
  low: number;
  close: number;
  upVolume: number;
  downVolume: number;
}

export type GetBarsParams = {
  symbol?: string;
};
